######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 28 23:58:58 2012
######################################################################

TEMPLATE = app
LANGUAGE = C++.
CONFIG += qt
# Input
SOURCES += hereKittyQT4.cpp
